# Generated by Django 3.2.3 on 2021-06-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_auto_20210628_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothing',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='clothing',
            new_name='item',
        ),
    ]
